version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - '.env'

  worker:
    build: .
    stdin_open: true
    tty: true
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/app:delegated
      - bundle:/usr/local/bundle:delegated
    depends_on:
      - redis
      - db
    env_file:
      - '.env'

  elasticsearch: 
    image: elasticsearch:6.5.0
    hostname: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  web:
    build: .
    container_name: web
    stdin_open: true
    tty: true
    command: "bash ./config/docker/startup.sh"
    volumes:
      - .:/app:delegated
      - "./config/docker/database.yml:/app/config/database.yml"
      - bundle:/usr/local/bundle:delegated
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
      - worker
      - elasticsearch
    env_file: 
      - '.env'

volumes:
  elasticsearch: {}
  db: {}
  redis: {}
  bundle: {}