version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: ./config/docker/Dockerfile
    image: chat-system
    container_name: web
    stdin_open: true
    tty: true
    command: "bash ./config/docker/startup.sh"
    volumes:
      - .:/app:delegated
      - "./config/docker/database.yml:/app/config/database.yml"
      - bundle:/usr/local/bundle:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - worker
    env_file: 
      - '.env'

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - '.env'

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    image: chat-system
    container_name: worker
    stdin_open: true
    tty: true
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - .:/app:delegated
      - bundle:/usr/local/bundle:delegated
    depends_on:
      - db
      - redis
    env_file:
      - '.env'

  elasticsearch: 
    image: elasticsearch:6.5.0
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: 'single-node'

volumes:
  db:
  bundle: